### ISSUE TITLE
NoClassDefError @ RegistryBuilder

### ISSUE THREAD

**Issue by Eladkay** [TeamAmeriFrance/Guide-API#50]
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/RegistryBuilder
    at amerifrance.guideapi.api.GuideAPI.<clinit>(GuideAPI.java:31)
    at amerifrance.guideapi.GuideMod.preInit(GuideMod.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

On init obviously, guide api 1.10.2-2.0.2-45

**Comment by TehNut** [comment]
Forge version?

**Comment by Eladkay** [comment]
2026, MC 1.10.2

**Comment by TehNut** [comment]
That is extremely outdated. Update.
