### ISSUE TITLE
Invalid/Dangerous prefix

### ISSUE THREAD

**Issue by Darkhax** [TeamAmeriFrance/Guide-API#78]
Forge now warns when an item is registered with a domain/prefix that is different from the active mod container. Noticed this in my logs earlier. 

Version 2.1.3-55
```
[12:16:19] [main/WARN]: ****************************************
[12:16:19] [main/WARN]: * Dangerous alternative prefix `cyclicmagic` for name `item.guideapi.book.cyclicmagic.guide`, expected `guideapi` invalid registry invocation/invalid name?
[12:16:19] [main/WARN]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
[12:16:19] [main/WARN]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:94)
[12:16:19] [main/WARN]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:66)
[12:16:19] [main/WARN]: *  at com.lothrazar.cyclicmagic.CyclicGuideBook.handlePost(CyclicGuideBook.java:162)
[12:16:19] [main/WARN]: *  at amerifrance.guideapi.GuideMod.postInit(GuideMod.java:69)
[12:16:19] [main/WARN]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[12:16:19] [main/WARN]: ****************************************
```

**Comment by TehNut** [comment]
Cyclic is using `setRegistryName` with just the `String` parameter. @PrinceOfAmber pls don't do that
